export const store = [
  {
    title: "adidas max air",
    price: "150,000",
    img: "images/five.png",
    weight: "0.5",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: "pending",
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
    category: "men's shoes",
  },
  {
    title: "Modern Wrist watch",
    price: "120,000",
    img: "images/four.png",
    weight: "0.8",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: "delivered",
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
    category: "wrist watches",
  },
  {
    title: "iphone 12",
    price: "350,000",
    img: "images/three.png",
    weight: "0.5",
    qty: "2",
    color: "black",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: "pending",
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
    category: "gadgets",
  },
  {
    title: "Nike Airforce",
    price: "24,000",
    img: "images/two.png",
    weight: "0.5",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: "delivered",
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
    category: "men's shoe",
  },
  {
    title: "T-Shirt",
    price: "5,000",
    img: "images/one.png",
    weight: "0.5",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: "delivered",
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
    category: "clothing",
  },
  {
    title: "MacBook Air 2020",
    price: "900,000",
    img: "images/six.png",
    weight: "0.5",
    qty: "2",
    color: "blue",
    customer: "Unuefe Ejoke, 08064491812",
    vendor: "Shimus Clothing and Accessories",
    address: "2, Sonola Street, Aguda-Ogba",
    orderStatus: "pending",
    orderDate: "June 12, 2022",
    deliveryDate: "June 14, 2022",
    category: "gadgets",
  },
];

export const notifications = [
  {
    subject: "summer sales coupon",
    receiver: "all",
    date: "jun 12, 2022",
    noteStatus: "delivered",
    message: `The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place.`,
  },
  {
    subject: "update business information",
    receiver: "vendors",
    date: "jun 12, 2022",
    noteStatus: "delivered",
    message: `The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place.`,
  },
  {
    subject: "brace up for black friday",
    receiver: "customers",
    date: "jun 12, 2022",
    noteStatus: "pending",
    message: `The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place.`,
  },
  {
    subject: "new update to privacy policy",
    receiver: "customers",
    date: "jun 12, 2022",
    noteStatus: "delivered",
    message: `The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place.`,
  },
  {
    subject: "new update",
    receiver: "all",
    date: "jun 12, 2022",
    noteStatus: "delivered",
    message: `The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place.`,
  },
  {
    subject: "summer sales coupon",
    receiver: "customers",
    date: "jun 12, 2022",
    noteStatus: "pending",
    message: `The shoes had been there for as long as anyone could remember. In fact, it was difficult for anyone to come up with a date they had first appeared. It had seemed they'd always been there and yet they seemed so out of place.`,
  },
];
export const vendors = [
  {
    name: "Nnamdi Oluwatosin",
    email: "simisola@elizabeth.com",
    tel: "07033295557",
    busName: "Daniel Inc",
    vendorStatus: "inactive",
    id: 0,
  },
  {
    name: "Ifeoma Oluwanisola",
    email: "xgbadamosi@adewale.net ",
    tel: "07033295557",
    busName: "Wilkinson and Aufderhar",
    vendorStatus: "active",
    id: 1,
  },
  {
    name: "Akande Adegboye",
    email: "zelizabeth@gmail.com",
    tel: "07033295557",
    busName: "AKT  Store",
    vendorStatus: "inactive",
    id: 2,
  },
  {
    name: "Adeboye Isokun ",
    email: "ikhidie76@adewale.ng ",
    tel: "07033295557",
    busName: "The4kStore",
    vendorStatus: "active",
    id: 3,
  },
  {
    name: "Adeboye Isokun ",
    email: "ikhidie76@adewale.ng ",
    tel: "07033295557",
    busName: "The4kStore",
    vendorStatus: "inactive",
    id: 4,
  },
  {
    name: "Nnamdi Oluwatosin",
    email: "simisola@elizabeth.com",
    tel: "07033295557",
    busName: "Daniel Inc",
    vendorStatus: "active",
    id: 5,
  },
  {
    name: "Ifeoma Oluwanisola",
    email: "xgbadamosi@adewale.net ",
    tel: "07033295557",
    busName: "Wilkinson and Aufderhar",
    vendorStatus: "inactive",
    id: 6,
  },
  {
    name: "Akande Adegboye",
    email: "zelizabeth@gmail.com",
    tel: "07033295557",
    busName: "AKT  Store",
    vendorStatus: "active",
    id: 7,
  },
  {
    name: "Adeboye Isokun ",
    email: "ikhidie76@adewale.ng ",
    tel: "07033295557",
    busName: "The4kStore",
    vendorStatus: "inactive",
    id: 8,
  },
  {
    name: "Adeboye Isokun ",
    email: "ikhidie76@adewale.ng ",
    tel: "07033295557",
    busName: "The4kStore",
    vendorStatus: "active",
    id: 9,
  },
];
export const users = [
  {
    name: "Adeboye Isokun ",
    email: "ikhidie76@adewale.ng ",
    tel: "07033295557",
    vendorStatus: "active",
  },
];
export const notify = [
  { title: "Okocha funded his wallet", desc: "Okocha just funded his wallet" },
  {
    title: "An order has been made",
    desc: "A user just ordered for sony playstation 5",
  },
  {
    title: "A Vendor just joined",
    desc: "New vendor has signed up, click here to view vendor details",
  },
  {
    title: "Completion of Order",
    desc: "An order has been sucessfully completed",
  },
];
